routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'auth','prefix' => 'admin'], function () {
    
    Route::get('/', 'Admin\AdminController@index');
    Route::resource('usuarios', 'Admin\UsuarioController');
  
    Route::get('usuarios/papel/{id}', ['as'=>'usuarios.papel','uses'=>'Admin\UsuarioController@papel']);
    Route::post('usuarios/papel/{papel}', ['as'=>'usuarios.papel.store','uses'=>'Admin\UsuarioController@papelStore']);
    Route::delete('usuarios/papel/{usuario}/{papel}', ['as'=>'usuarios.papel.destroy','uses'=>'Admin\UsuarioController@papelDestroy']);
  
    Route::resource('papeis', 'Admin\PapelController');
  
    Route::get('papeis/permissao/{id}', ['as'=>'papeis.permissao','uses'=>'Admin\PapelController@permissao']);
    Route::post('papeis/permissao/{permissao}', ['as'=>'papeis.permissao.store','uses'=>'Admin\PapelController@permissaoStore']);
    Route::delete('papeis/permissao/{papel}/{permissao}', ['as'=>'papeis.permissao.destroy','uses'=>'Admin\PapelController@permissaoDestroy']);
  
    Route::get('imagens/excluidas', ['as'=>'imagens.excluidas','uses'=>'Admin\ImagemController@excluidas']);
    Route::put('imagens/recupera/{id}', ['as'=>'imagens.recupera','uses'=>'Admin\ImagemController@recupera']);
  
    Route::resource('imagens', 'Admin\ImagemController');
    
    Route::resource('processos', 'Admin\ProcessoController');

  
    Route::get('perfil', ['as'=>'site.perfil','uses'=>'Site\SiteController@perfil']);
    Route::put('perfil', ['as'=>'site.perfil.update','uses'=>'Site\SiteController@perfilUpdate']);
  
    Route::get('favoritos', ['as'=>'site.favoritos','uses'=>'Site\SiteController@favoritos']);
  
    Route::post('favoritos/{carro}', ['as'=>'site.favoritos.create','uses'=>'Site\SiteController@favoritosCreate']);
    Route::delete('favoritos/{carro}', ['as'=>'site.favoritos.delete','uses'=>'Site\SiteController@favoritosDelete']);
  });
  

app/Http/Controllers/Admin/ImagemController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Imagem;
use Illuminate\Support\Facades\Gate;
use Intervention\Image\ImageManagerStatic as Image;
use Validator;

class ImagemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      if(Gate::denies('imagens-view')){
        abort(403,"Não autorizado!");
      }

      $registros = Imagem::where('deletado','=','N')->orderBy('id','DESC')->paginate(5);
      $caminhos = [
      ['url'=>'/admin','titulo'=>'Admin'],
      ['url'=>'','titulo'=>'Imagens']
      ];
      return view('admin.imagem.index',compact('registros','caminhos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Gate::denies('imagens-create')){
          abort(403,"Não autorizado!");
        }

        $caminhos = [
        ['url'=>'/admin','titulo'=>'Admin'],
        ['url'=>route('imagens.index'),'titulo'=>'Imagens'],
        ['url'=>'','titulo'=>'Adicionar']
        ];

        return view('admin.imagem.adicionar',compact('caminhos'));


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Gate::denies('imagens-create')){
          abort(403,"Não autorizado!");
        }

        if($request->hasFile('imagens')){

          $imagens = $request->imagens;

          $imagemRegras = array(
            'imagem' => 'required|image|dimensions:min_width=600,min_height=600',
          );

          foreach($imagens as $imagem){
            $imagemArray = array('imagem' => $imagem);
            $imageValidator = Validator::make($imagemArray, $imagemRegras);
            if ($imageValidator->fails()) {
              return redirect()->route('imagens.create')
                          ->withErrors($imageValidator)
                          ->withInput();
            }
          }

          foreach ($imagens as $imagem) {
            $imagem_nome = time().$imagem->getClientOriginalName();
            $imagem->move("imagens/",$imagem_nome);

            $tamPeq = explode("x",config('app.imagemPequena'));
            $tamG = explode("x",config('app.imagemGaleria'));
            $tamS = explode("x",config('app.imagemSlide'));

            $image1 = Image::make("imagens/".$imagem_nome)->fit($tamPeq[0],$tamPeq[1])->save("imagens/pequena-".$imagem_nome);
            $image2 = Image::make("imagens/".$imagem_nome)->fit($tamG[0],$tamG[1])->save("imagens/galeria-".$imagem_nome);
            $image3 = Image::make("imagens/".$imagem_nome)->fit($tamS[0],$tamS[1])->save("imagens/slide-".$imagem_nome);

            $auxNome = explode(".",$imagem->getClientOriginalName());
            $imagemModel = Imagem::create(["titulo"=>$auxNome[0],"descricao"=>""]);
            $imagemModel->arquivos()->create(["url"=>"imagens/pequena-".$imagem_nome,"tamanho"=>"P"]);
            $imagemModel->arquivos()->create(["url"=>"imagens/galeria-".$imagem_nome,"tamanho"=>"G"]);
            $imagemModel->arquivos()->create(["url"=>"imagens/slide-".$imagem_nome,"tamanho"=>"S"]);

          }

        }

        return redirect()->route('imagens.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Gate::denies('imagens-edit')){
          abort(403,"Não autorizado!");
        }

        $registro = Imagem::find($id);

        $caminhos = [
        ['url'=>'/admin','titulo'=>'Admin'],
        ['url'=>route('imagens.index'),'titulo'=>'Imagens'],
        ['url'=>'','titulo'=>'Editar']
        ];

        return view('admin.imagem.editar',compact('caminhos','registro'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Gate::denies('imagens-edit')){
          abort(403,"Não autorizado!");
        }
        $this->validate($request, [
          'titulo' => 'required',
        ]);
        $registro = Imagem::find($id);
        $registro->update($request->all());

        if($request->hasFile('imagem')){
          $this->validate($request, [
                'imagem' => 'required|image|dimensions:min_width=600,min_height=600',
          ]);

          $imagem = $request->file('imagem');

          $imagem_nome = time().$imagem->getClientOriginalName();
          $imagem->move("imagens/",$imagem_nome);

          $tamPeq = explode("x",config('app.imagemPequena'));
          $tamG = explode("x",config('app.imagemGaleria'));
          $tamS = explode("x",config('app.imagemSlide'));

          $image1 = Image::make("imagens/".$imagem_nome)->fit($tamPeq[0],$tamPeq[1])->save("imagens/pequena-".$imagem_nome);
          $image2 = Image::make("imagens/".$imagem_nome)->fit($tamG[0],$tamG[1])->save("imagens/galeria-".$imagem_nome);
          $image3 = Image::make("imagens/".$imagem_nome)->fit($tamS[0],$tamS[1])->save("imagens/slide-".$imagem_nome);

          $auxNome = explode(".",$imagem->getClientOriginalName());

          $imagPequena = $registro->arquivos()->where('tamanho','=','P')->first();
          $imagGaleria = $registro->arquivos()->where('tamanho','=','G')->first();
          $imagSlide = $registro->arquivos()->where('tamanho','=','S')->first();

          $imagPequena->update(["url"=>"imagens/pequena-".$imagem_nome]);
          $imagGaleria->update(["url"=>"imagens/galeria-".$imagem_nome]);
          $imagSlide->update(["url"=>"imagens/slide-".$imagem_nome]);

        }

        return redirect()->route('imagens.edit',$id);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Gate::denies('imagens-delete')){
          abort(403,"Não autorizado!");
        }

        Imagem::find($id)->update(['deletado'=>'S']);

        return redirect()->route('imagens.index');

    }

    public function excluidas()
    {
      if(Gate::denies('imagens-edit')){
        abort(403,"Não autorizado!");
      }

      $registros = Imagem::where('deletado','=','S')->orderBy('id','DESC')->paginate(5);
      $caminhos = [
      ['url'=>'/admin','titulo'=>'Admin'],
      ['url'=>route('imagens.index'),'titulo'=>'Imagens'],
      ['url'=>'','titulo'=>'Excluídas']
      ];
      return view('admin.imagem.excluidas',compact('registros','caminhos'));
    }

    public function recupera($id)
    {
        if(Gate::denies('imagens-edit')){
          abort(403,"Não autorizado!");
        }

        Imagem::find($id)->update(['deletado'=>'N']);

        return redirect()->route('imagens.excluidas');

    }
}

resources/views/admin/imagem/_form.blade.php
<div class="file-field input-field">
  <div class="btn">
    <span>Carregar imagens</span>
    <input type="file" multiple name="imagens[]">
  </div>
  <div class="file-path-wrapper">
    <input class="file-path validate" type="text">
  </div>
</div>

resources/views/admin/imagem/adicionar.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h2 class="center">Adicionar Imagem</h2>

	@if (count($errors) > 0)
		<div class="row">
        <div class="col s12">
          <div class="card red darken-1">
            <div class="card-content white-text">
              <span class="card-title">Erros</span>
							@foreach ($errors->all() as $message)
					        <li>{{$message}}</li>
					    @endforeach
            </div>
          </div>
        </div>
      </div>
  @endif

	@include('admin._caminho')

	<div class="row">
		<form action="{{ route('imagens.store') }}" method="post" enctype="multipart/form-data">

		{{csrf_field()}}
		@include('admin.imagem._form')

		<button class="btn green">Adicionar</button>


		</form>

	</div>

</div>


@endsection

resources/views/admin/imagem/editar.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h2 class="center">Editar Imagem</h2>
	@if (count($errors) > 0)
		<div class="row">
        <div class="col s12">
          <div class="card red darken-1">
            <div class="card-content white-text">
              <span class="card-title">Erros</span>
					@foreach ($errors->all() as $message)
			        <li>{{$message}}</li>
				    @endforeach
            </div>
          </div>
        </div>
      </div>
  @endif
	@include('admin._caminho')
	<div class="row">
		<form action="{{ route('imagens.update',$registro->id) }}" method="post" enctype="multipart/form-data">

		{{csrf_field()}}
		{{ method_field('PUT') }}
		<div class="input-field">
			<input type="text" name="titulo" class="validade" value="{{ isset($registro->titulo) ? $registro->titulo : '' }}">
			<label>Título</label>
		</div>

		<div class="input-field">
			<input type="text" name="descricao" class="validade" value="{{ isset($registro->descricao) ? $registro->descricao : '' }}">
			<label>Descrição</label>
		</div>
		<div class="file-field input-field">
		  <div class="btn">
		    <span>Atualizar imagem</span>
		    <input type="file" name="imagem">
		  </div>
		  <div class="file-path-wrapper">
		    <input class="file-path validate" type="text">
		  </div>
		</div>

		<button class="btn blue">Atualizar</button>

		<h3>Tamanhos gerados</h3>

		<div class="row">
			 <div class="col s12 m3">
				 <div class="card">
					 <div class="card-image">
						 <img class="materialboxed" src="{{$registro->pequenaUrl()}}">

					 </div>
					 <div class="card-content">
						 <strong>Pequena</strong>
						 <p>{{config('app.imagemPequena')}}</p>
					 </div>
				 </div>
			 </div>
			 <div class="col s12 m4">
				 <div class="card">
					 <div class="card-image">
						 <img class="materialboxed" src="{{$registro->galeriaUrl()}}">

					 </div>
					 <div class="card-content">
						 <strong>Galeria</strong>
						 <p>{{config('app.imagemGaleria')}}</p>
					 </div>
				 </div>
			 </div>
			 <div class="col s12 m5">
				 <div class="card">
					 <div class="card-image">
						 <img class="materialboxed" src="{{$registro->slideUrl()}}">

					 </div>
					 <div class="card-content">
						 <strong>Slide</strong>
						 <p>{{config('app.imagemSlide')}}</p>
					 </div>
				 </div>
			 </div>
		 </div>

		</form>

	</div>

</div>


@endsection

resources/views/admin/imagem/excluidas.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<h2 class="center">Lista de Imagens Excluídas</h2>

		@include('admin._caminho')
		<div class="row">
			<table>
				<thead>
					<tr>
						<th>Id</th>
						<th>Título</th>
						<th>Descrição</th>
						<th>Imagem</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
				@foreach($registros as $registro)
					<tr>
						<td>{{ $registro->id }}</td>
						<td>{{ $registro->titulo }}</td>
						<td>{{ $registro->descricao }}</td>
						<td><img width="50" class="materialboxed" src="{{$registro->galeriaUrl()}}" alt="{{$registro->titulo}}"></td>

						<td>


							<form action="{{route('imagens.recupera',$registro->id)}}" method="post">

								@can('imagens-delete')
									{{ method_field('PUT') }}
									{{ csrf_field() }}
									<button title="Recuperar" class="btn green"><i class="material-icons">restore</i></button>
								@endcan
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>

		</div>
		<div class="row">
			@can('imagens-create')
			<a class="btn blue" href="{{route('imagens.index')}}">Voltar</a>
			@endcan

		</div>

		<div align="center" class="row">
			{{ $registros->links() }}
		</div>
	</div>

@endsection

resources/views/admin/imagem/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<h2 class="center">Lista de Imagens</h2>

		@include('admin._caminho')
		<div class="row">
			<table>
				<thead>
					<tr>
						<th>Id</th>
						<th>Título</th>
						<th>Descrição</th>
						<th>Imagem</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
				@foreach($registros as $registro)
					<tr>
						<td>{{ $registro->id }}</td>
						<td>{{ $registro->titulo }}</td>
						<td>{{ $registro->descricao }}</td>
						<td><img width="50" class="materialboxed" src="{{$registro->galeriaUrl()}}" alt="{{$registro->titulo}}"></td>

						<td>


							<form action="{{route('imagens.destroy',$registro->id)}}" method="post">
								@can('imagens-edit')
								<a title="Editar" class="btn orange" href="{{ route('imagens.edit',$registro->id) }}"><i class="material-icons">mode_edit</i></a>

								@endcan
								@can('imagens-delete')
									{{ method_field('DELETE') }}
									{{ csrf_field() }}
									<button title="Deletar" class="btn red"><i class="material-icons">delete</i></button>
								@endcan
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>

		</div>
		<div class="row">
			@can('imagens-create')
			<a class="btn blue" href="{{route('imagens.create')}}">Adicionar</a>
			@endcan

			@can('imagens-edit')
			<a class="btn red" href="{{route('imagens.excluidas')}}">Excluídas</a>
			@endcan
		</div>

		<div align="center" class="row">
			{{ $registros->links() }}
		</div>
	</div>

@endsection