routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'auth','prefix' => 'admin'], function () {
    
    Route::get('/', 'Admin\AdminController@index');
    Route::resource('usuarios', 'Admin\UsuarioController');
  
    Route::get('usuarios/papel/{id}', ['as'=>'usuarios.papel','uses'=>'Admin\UsuarioController@papel']);
    Route::post('usuarios/papel/{papel}', ['as'=>'usuarios.papel.store','uses'=>'Admin\UsuarioController@papelStore']);
    Route::delete('usuarios/papel/{usuario}/{papel}', ['as'=>'usuarios.papel.destroy','uses'=>'Admin\UsuarioController@papelDestroy']);
  
    Route::resource('papeis', 'Admin\PapelController');
  
    Route::get('papeis/permissao/{id}', ['as'=>'papeis.permissao','uses'=>'Admin\PapelController@permissao']);
    Route::post('papeis/permissao/{permissao}', ['as'=>'papeis.permissao.store','uses'=>'Admin\PapelController@permissaoStore']);
    Route::delete('papeis/permissao/{papel}/{permissao}', ['as'=>'papeis.permissao.destroy','uses'=>'Admin\PapelController@permissaoDestroy']);
  
    Route::get('imagens/excluidas', ['as'=>'imagens.excluidas','uses'=>'Admin\ImagemController@excluidas']);
    Route::put('imagens/recupera/{id}', ['as'=>'imagens.recupera','uses'=>'Admin\ImagemController@recupera']);
  
    Route::resource('imagens', 'Admin\ImagemController');
    
    Route::resource('processos', 'Admin\ProcessoController');

  
    Route::get('perfil', ['as'=>'site.perfil','uses'=>'Site\SiteController@perfil']);
    Route::put('perfil', ['as'=>'site.perfil.update','uses'=>'Site\SiteController@perfilUpdate']);
  
    Route::get('favoritos', ['as'=>'site.favoritos','uses'=>'Site\SiteController@favoritos']);
  
    Route::post('favoritos/{carro}', ['as'=>'site.favoritos.create','uses'=>'Site\SiteController@favoritosCreate']);
    Route::delete('favoritos/{carro}', ['as'=>'site.favoritos.delete','uses'=>'Site\SiteController@favoritosDelete']);
  });
  

resources/views/admin/_caminho.blade.php
<div class="row">
	<nav>
		<div class="nav-wrapper {{config('app.corSite')}}">
		  <div class="col s12">
		  	@if(isset($caminhos))
			  	@foreach($caminhos as $caminho)
				  	@if($caminho['url'])
				    <a href="{{$caminho['url']}}" class="breadcrumb">{{$caminho['titulo']}}</a>
				    @else
				    	<span class="breadcrumb">{{$caminho['titulo']}}</span>
				    @endif

			    @endforeach
		    @else
		     <span class="breadcrumb">Admin</span>
		    @endif
		  </div>
		</div>
	</nav>
</div>

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row center">
      <h2>Admin</h2>
    </div>

    @include('admin._caminho')

    <div class="row">
      @can('carros-view')
        <div class="col s12 m6">
          <div class="card orange darken-2">
            <div class="card-content white-text">
              <span class="card-title">Carros</span>
              <p>Lista de Carros</p>
            </div>
            <div class="card-action">
              <a href="{{route('carros.index')}}">Visualizar</a>
            </div>
          </div>
        </div>
      @endcan
      @can('imagens-view')
        <div class="col s12 m6">
          <div class="card red darken-2">
            <div class="card-content white-text">
              <span class="card-title">Imagens</span>
              <p>Lista de Imagens</p>
            </div>
            <div class="card-action">
              <a href="{{route('imagens.index')}}">Visualizar</a>
            </div>
          </div>
        </div>
      @endcan
      @can('usuario-view')
        <div class="col s12 m6">
          <div class="card purple darken-2">
            <div class="card-content white-text">
              <span class="card-title">Usuários</span>
              <p>Usuários do sistema</p>
            </div>
            <div class="card-action">
              <a href="{{route('usuarios.index')}}">Visualizar</a>
            </div>
          </div>
        </div>
      @endcan
      @can('slides-view')
        <div class="col s12 m6">
          <div class="card yellow darken-2">
            <div class="card-content white-text">
              <span class="card-title">Slides</span>
              <p>Lista de Slides</p>
            </div>
            <div class="card-action">
              <a href="{{route('slides.index')}}">Visualizar</a>
            </div>
          </div>
        </div>
      @endcan
      @can('favoritos-view')
        <div class="col s12 m6">
          <div class="card blue">
            <div class="card-content white-text">
              <span class="card-title">Favoritos</span>
              <p>Lista de carros favoritos</p>
            </div>
            <div class="card-action">
              <a href="{{route('site.favoritos')}}">Visualizar</a>
            </div>
          </div>
        </div>
      @endcan
      @can('perfil-view')
        <div class="col s12 m6">
          <div class="card green">
            <div class="card-content white-text">
              <span class="card-title">Perfil</span>
              <p>Alterar dados do perfil</p>
            </div>
            <div class="card-action">
              <a href="{{route('site.perfil')}}">Visualizar</a>
            </div>
          </div>
        </div>
      @endcan
      @can('papel-view')
        <div class="col s12 m6">
          <div class="card orange darken-4">
            <div class="card-content white-text">
              <span class="card-title">Papéis</span>
              <p>Listar papéis do sistema</p>
            </div>
            <div class="card-action">
              <a href="{{route('papeis.index')}}">Visualizar</a>
            </div>
          </div>
        </div>
        @endcan
      </div>


</div>
@endsection