routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'auth','prefix' => 'admin'], function () {
    
    Route::get('/', 'Admin\AdminController@index');
    Route::resource('usuarios', 'Admin\UsuarioController');
  
    Route::get('usuarios/papel/{id}', ['as'=>'usuarios.papel','uses'=>'Admin\UsuarioController@papel']);
    Route::post('usuarios/papel/{papel}', ['as'=>'usuarios.papel.store','uses'=>'Admin\UsuarioController@papelStore']);
    Route::delete('usuarios/papel/{usuario}/{papel}', ['as'=>'usuarios.papel.destroy','uses'=>'Admin\UsuarioController@papelDestroy']);
  
    Route::resource('papeis', 'Admin\PapelController');
  
    Route::get('papeis/permissao/{id}', ['as'=>'papeis.permissao','uses'=>'Admin\PapelController@permissao']);
    Route::post('papeis/permissao/{permissao}', ['as'=>'papeis.permissao.store','uses'=>'Admin\PapelController@permissaoStore']);
    Route::delete('papeis/permissao/{papel}/{permissao}', ['as'=>'papeis.permissao.destroy','uses'=>'Admin\PapelController@permissaoDestroy']);
  
    Route::get('imagens/excluidas', ['as'=>'imagens.excluidas','uses'=>'Admin\ImagemController@excluidas']);
    Route::put('imagens/recupera/{id}', ['as'=>'imagens.recupera','uses'=>'Admin\ImagemController@recupera']);
  
    Route::resource('imagens', 'Admin\ImagemController');
    
    Route::resource('processos', 'Admin\ProcessoController');

  
    Route::get('perfil', ['as'=>'site.perfil','uses'=>'Site\SiteController@perfil']);
    Route::put('perfil', ['as'=>'site.perfil.update','uses'=>'Site\SiteController@perfilUpdate']);
  
    Route::get('favoritos', ['as'=>'site.favoritos','uses'=>'Site\SiteController@favoritos']);
  
    Route::post('favoritos/{carro}', ['as'=>'site.favoritos.create','uses'=>'Site\SiteController@favoritosCreate']);
    Route::delete('favoritos/{carro}', ['as'=>'site.favoritos.delete','uses'=>'Site\SiteController@favoritosDelete']);
  });
  

app/Processo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Processo extends Model
{
    protected $table = "processos";
    protected $fillable = [
      "titulo","descricao"
    ];
}

app/Http/Controllers/Admin/ProcessoController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Gate;

use App\Processo;

class ProcessoController extends Controller
{
    public function index()
    {
        $registros = Processo::orderBy('id','DESC')->paginate(5);
        $caminhos = [
            ['url'=>'','titulo'=>'Admin']
        ];
        return view('admin.processo.index',compact('caminhos', 'registros'));
    }

    public function create()
    {
   

      $caminhos = [
      ['url'=>'/admin','titulo'=>'Admin'],
      ['url'=>route('processos.index'),'titulo'=>'Processos'],
      ['url'=>'','titulo'=>'Adicionar']
      ];

      return view('admin.processo.adicionar',compact('caminhos','marcas','categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
            'titulo' => 'required',
            'descricao' => 'required',
            'valor' => 'required|numeric',
            'ano' => 'required|numeric',
            'marca_id' => 'required|numeric',
      ]);

      $dados = $request->all();

      $carro = Carro::create($request->all());
      if(isset($dados['novasCategorias'])){
        foreach ($dados['novasCategorias'] as $key => $value) {
          $carro->categorias()->save(Categoria::find($value));
        }
      }

      return redirect()->route('carros.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Carro $carro)
    {
      if(Gate::denies('carros-edit')){
        abort(403,"Não autorizado!");
      }

      $registro = $carro;

      $marcas = Marca::all();
      $categorias = Categoria::all();

      $caminhos = [
      ['url'=>'/admin','titulo'=>'Admin'],
      ['url'=>route('carros.index'),'titulo'=>'Carros'],
      ['url'=>'','titulo'=>'Editar']
      ];

      return view('admin.carro.editar',compact('registro','caminhos','marcas','categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Carro $carro)
    {
      if(Gate::denies('carros-edit')){
        abort(403,"Não autorizado!");
      }

      $this->validate($request, [
            'titulo' => 'required',
            'descricao' => 'required',
            'valor' => 'required|numeric',
            'ano' => 'required|numeric',
            'marca_id' => 'required|numeric',
      ]);

      $dados = $request->all();
      $registro = $carro;

      $registro->update($request->all());
      foreach ($registro->categorias as $key => $value) {
        $registro->categorias()->detach($value);
      }
      if(isset($dados['novasCategorias'])){
        foreach ($dados['novasCategorias'] as $key => $value) {
          $registro->categorias()->save(Categoria::find($value));
        }
      }

      return redirect()->route('carros.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Carro $carro)
    {
      if(Gate::denies('carros-delete')){
        abort(403,"Não autorizado!");
      }

      foreach ($carro->categorias as $key => $value) {
        $carro->categorias()->detach($value);
      }

      foreach ($carro->imagens as $key => $value) {
        $value->delete();
      }

      $carro->delete();
      return redirect()->route('carros.index');
    }

}

resources/views/admin/processo/_form.blade.php
<div class="form-group">
<div class="form-group col-md-2">
  <label>Número Processo</label>
	<input type="text" name="nprocesso" class="form-control" value="{{ isset($registro->nprocesso) && !old('nprocesso') ? $registro->nprocesso : '' }}{{old('nprocesso')}}">
</div>

<div class="form-group col-md-6">
  <label>Assunto</label>
	<input type="text" name="titulo" class="form-control" value="{{ isset($registro->titulo) && !old('titulo') ? $registro->titulo : '' }}{{old('titulo')}}">
</div>

<div class="form-group col-md-2">
  <label>Ano</label>
	<input type="text" name="ano" class="form-control" value="{{ isset($registro->ano) && !old('ano') ? $registro->ano : '' }}{{old('ano')}}">
</div>

<div class="form-group col-md-2">
  <label>caixa</label>
	<input type="text" name="caixa" class="form-control" value="{{ isset($registro->caixa) && !old('caixa') ? $registro->caixa : '' }}{{old('caixa')}}">	
</div>
</div>

resources/views/admin/processo/adicionar.blade.php
@extends('layouts.app')

@section('content')
	<div class="row">
	<div class="col-md-12">
				<!-- TABLE STRIPED -->
				<div class="panel">
					<div class="panel-body">

						<form action="{{ route('processos.store') }}" method="post">
						{{csrf_field()}}
						@include('admin.processo._form')
						<div class="form-group col-md-2">
						<button class="btn btn-success">Adicionar</button>
						</div>
						</form>

					</div>
				</div>
	</div>
	</div>
@endsection

resources/views/admin/processo/editar.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h2 class="center">Editar carros</h2>
	@if (count($errors) > 0)
		<div class="row">
        <div class="col s12">
          <div class="card red darken-1">
            <div class="card-content white-text">
              <span class="card-title">Erros</span>
							@foreach ($errors->all() as $message)
					        <li>{{$message}}</li>
					    @endforeach
            </div>
          </div>
        </div>
      </div>
  @endif
	@include('admin._caminho')
	<div class="row">
		<form action="{{ route('carros.update',$registro) }}" method="post">

		{{csrf_field()}}
		{{ method_field('PUT') }}
		@include('admin.carro._form')

		<button class="btn blue">Atualizar</button>


		</form>

	</div>

</div>


@endsection

resources/views/admin/processo/editargaleria.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h2 class="center">Editar Galeria</h2>
	@if (count($errors) > 0)
		<div class="row">
        <div class="col s12">
          <div class="card red darken-1">
            <div class="card-content white-text">
              <span class="card-title">Erros</span>
							@foreach ($errors->all() as $message)
					        <li>{{$message}}</li>
					    @endforeach
            </div>
          </div>
        </div>
      </div>
  @endif
	@include('admin._caminho')
	<div class="row">
		<form action="{{ route('carros.galeria.update',$registro) }}" method="post">

		{{csrf_field()}}
		{{ method_field('PUT') }}

		<div class="input-field">
			<input type="text" name="titulo" class="validade" value="{{ isset($registro->titulo) ? $registro->titulo : '' }}{{old('titulo')}}">
			<label>Título</label>
		</div>

		<div class="input-field">
			<input type="text" name="descricao" class="validade" value="{{ isset($registro->descricao) ? $registro->descricao : '' }}{{old('descricao')}}">
			<label>Descrição</label>
		</div>

		<div class="input-field">
			<input type="text" name="ordem" class="validade" value="{{ isset($registro->ordem) ? $registro->ordem : '' }}{{old('ordem')}}">
			<label>Ordem</label>
		</div>

		<button class="btn blue">Atualizar</button>


		</form>

	</div>

</div>


@endsection

resources/views/admin/processo/galeria.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<h2 class="center">Galeria de imagens</h2>

		@include('admin._caminho')
		<div class="row">
			<table>
				<thead>
					<tr>
						<th>Imagem</th>
						<th>Título</th>
						<th>Descrição</th>
						<th>Ordem</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
				@foreach($registros as $registro)
					<tr>
            <td><img width="50" class="materialboxed" src="{{ $registro->url }}"></td>

						<td>{{ $registro->titulo ? $registro->titulo : '---' }}</td>
						<td>{{ $registro->descricao ? $registro->descricao : '---' }}</td>
						<td>{{ $registro->ordem }}</td>


						<td>

              <form action="{{route('carros.galeria.delete',$registro)}}" method="post">
								@can('carros-edit')
								<a title="Editar" class="btn orange" href="{{route('carros.galeria.edit',$registro)}}"><i class="material-icons">mode_edit</i></a>

								@endcan
								@can('carros-delete')
									{{ method_field('DELETE') }}
									{{ csrf_field() }}
									<button title="Deletar" class="btn red"><i class="material-icons">delete</i></button>
								@endcan
							</form>

						</td>
					</tr>
				@endforeach
				</tbody>
			</table>

		</div>
		<div class="row">
			@can('carros-create')
			<a class="btn blue" href="{{route('carros.galeria.create',$carro)}}">Adicionar</a>
			@endcan
		</div>

		<div align="center" class="row">
			{{ $registros->links() }}
		</div>

	</div>

@endsection

resources/views/admin/processo/imagens.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

  <h2 class="center">Selecionar imagens</h2>
  @include('admin._caminho')
  <div class="row">

  <?php $conta = 0; ?>
  @foreach($imagens as $imagem)
    <?php $imagem->selecionado = false; ?>
    @if($imagensCarro)
      @foreach($imagensCarro as $value)
        @if($value->imagem_id == $imagem->id)
          <?php $imagem->selecionado = true; ?>
        @endif
      @endforeach
    @endif

       <div class="col s12 m4">
         <div class="card">
           <div class="card-image">
             <img class="materialboxed" src="{{$imagem->pequenaUrl()}}">

           </div>
           <div class="card-content">
             <strong>{{$imagem->titulo}}</strong>
           </div>
           <div class="card-action" id="divID{{$imagem->id}}">
             @if($imagem->selecionado)
               <a onclick="removeImagem({{$imagem->id}},'divID{{$imagem->id}}')" class="btn green">Remover imagem</a>
             @else
                <a onclick="selecionaImagem({{$imagem->id}},'divID{{$imagem->id}}')" class="btn blue">Selecionar imagem</a>
             @endif

           </div>
         </div>
       </div>

       <?php $conta++; ?>
       @if($conta == 3)
         <?php $conta=0; ?>
         </div>
         <div class="row">
       @endif

  @endforeach
  </div>

  <div align="center" class="row">
    {{ $imagens->links() }}
  </div>

  <div class="row">
    @can('carros-view')
    <a class="btn blue" href="{{route('carros.galeria.index',$carro)}}">Voltar</a>
    @endcan

  </div>

  <script type="text/javascript">

    function selecionaImagem(id,divID){
      $('#'+divID).html('<button class="btn orange">Processando..</button>');
      $.ajax({
          headers: {
              'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
          },
          type: 'POST',
          url: "{{route('carros.galeria.store')}}",
          data: 'id='+id+'&carro={{$carro->id}}',
          success: function(data){
              console.log(data);
              $('#'+divID).html('<button onclick="removeImagem('+id+',\''+divID+'\')" class="btn green">Remover imagem</button>');
          },
          error: function(){
              $('#'+divID).html('<a onclick="selecionaImagem('+id+',\''+divID+'\')" class="btn blue">Selecionar imagem</a>');
          }
      });
    }
    function removeImagem(id,divID){
        $('#'+divID).html('<button class="btn orange">Processando..</button>');
        $.ajax({
            headers: {
                'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            },
            type: 'DELETE',
            url: "{{route('carros.galeria.remove')}}",
            data: 'id='+id+'&carro={{$carro->id}}',
            success: function(data){
                console.log(data);
                $('#'+divID).html('<a onclick="selecionaImagem('+id+',\''+divID+'\')" class="btn blue">Selecionar imagem</a>');
            },
            error: function(){
                $('#'+divID).html('<button onclick="removeImagem('+id+',\''+divID+'\')" class="btn green">Remover imagem</button>');
            }
        });
    }

  </script>


</div>
@endsection

resources/views/admin/processo/index.blade.php
@extends('layouts.app')

@section('content')


		
		<div class="row">
			<div class="col-md-12">
				<!-- TABLE STRIPED -->
				<div class="panel">
					<div class="panel-heading">
						<!-- <h3 class="panel-title">@include('admin._caminho')</h3>-->
						<a title="Novo Processo" class="btn btn-success" href="{{ route('processos.create')}}"><i class="material-icons">Novo Processo</i></a>
					</div>
					<div class="panel-body">
						<table class="table table-striped">
							<thead>
								<tr>
									<th>#</th>
									<th>Número Processo</th>
									<th>Assunto</th>
									<th>Caixa</th>
								</tr>
							</thead>
							<tbody>
							@foreach($registros as $registro)
							<tr>
								<td>{{ $registro->id }}</td>
								<td>{{ $registro->titulo }}</td>
								<td>{{ $registro->descricao }}</td>
								<td>

									<form action="" method="post">
										@can('carros-edit')
										<a title="Editar" class="btn orange" href=""><i class="material-icons">mode_edit</i></a>
										<a title="Galeria" class="btn blue" href=""><i class="material-icons">image</i></a>

										@endcan
										@can('carros-delete')
											{{ method_field('DELETE') }}
											{{ csrf_field() }}
											<button title="Deletar" class="btn red"><i class="material-icons">delete</i></button>
										@endcan
									</form>

								</td>
							</tr>
							@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>

@endsection