routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'auth','prefix' => 'admin'], function () {
    
    Route::get('/', 'Admin\AdminController@index');
    Route::resource('usuarios', 'Admin\UsuarioController');
  
    Route::get('usuarios/papel/{id}', ['as'=>'usuarios.papel','uses'=>'Admin\UsuarioController@papel']);
    Route::post('usuarios/papel/{papel}', ['as'=>'usuarios.papel.store','uses'=>'Admin\UsuarioController@papelStore']);
    Route::delete('usuarios/papel/{usuario}/{papel}', ['as'=>'usuarios.papel.destroy','uses'=>'Admin\UsuarioController@papelDestroy']);
  
    Route::resource('papeis', 'Admin\PapelController');
  
    Route::get('papeis/permissao/{id}', ['as'=>'papeis.permissao','uses'=>'Admin\PapelController@permissao']);
    Route::post('papeis/permissao/{permissao}', ['as'=>'papeis.permissao.store','uses'=>'Admin\PapelController@permissaoStore']);
    Route::delete('papeis/permissao/{papel}/{permissao}', ['as'=>'papeis.permissao.destroy','uses'=>'Admin\PapelController@permissaoDestroy']);
  
    Route::get('imagens/excluidas', ['as'=>'imagens.excluidas','uses'=>'Admin\ImagemController@excluidas']);
    Route::put('imagens/recupera/{id}', ['as'=>'imagens.recupera','uses'=>'Admin\ImagemController@recupera']);
  
    Route::resource('imagens', 'Admin\ImagemController');
    
    Route::resource('processos', 'Admin\ProcessoController');

  
    Route::get('perfil', ['as'=>'site.perfil','uses'=>'Site\SiteController@perfil']);
    Route::put('perfil', ['as'=>'site.perfil.update','uses'=>'Site\SiteController@perfilUpdate']);
  
    Route::get('favoritos', ['as'=>'site.favoritos','uses'=>'Site\SiteController@favoritos']);
  
    Route::post('favoritos/{carro}', ['as'=>'site.favoritos.create','uses'=>'Site\SiteController@favoritosCreate']);
    Route::delete('favoritos/{carro}', ['as'=>'site.favoritos.delete','uses'=>'Site\SiteController@favoritosDelete']);
  });
  

app/Http/Controllers/Admin/PapelController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Papel;
use App\Permissao;
use Illuminate\Support\Facades\Gate;

class PapelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

      if(Gate::denies('papel-view')){
        abort(403,"Não autorizado!");
      }

      $registros = Papel::all();
      $caminhos = [
      ['url'=>'/admin','titulo'=>'Admin'],
      ['url'=>'','titulo'=>'Papéis']
      ];
      return view('admin.papel.index',compact('registros','caminhos'));
    }

    public function permissao($id)
    {
      if(Gate::denies('papel-edit')){
        abort(403,"Não autorizado!");
      }

      $papel = Papel::find($id);
      $permissao = Permissao::all();
      $caminhos = [
          ['url'=>'/admin','titulo'=>'Admin'],
          ['url'=>route('papeis.index'),'titulo'=>'Papéis'],
          ['url'=>'','titulo'=>'Permissões'],
      ];
      return view('admin.papel.permissao',compact('papel','permissao','caminhos'));
    }

    public function permissaoStore(Request $request,$id)
    {
        if(Gate::denies('papel-edit')){
          abort(403,"Não autorizado!");
        }
        $papel = Papel::find($id);
        $dados = $request->all();
        $permissao = Permissao::find($dados['permissao_id']);
        $papel->adicionaPermissao($permissao);
        return redirect()->back();
    }

    public function permissaoDestroy($id,$permissao_id)
    {
      if(Gate::denies('papel-edit')){
        abort(403,"Não autorizado!");
      }

      $papel = Papel::find($id);
      $permissao = Permissao::find($permissao_id);
      $papel->removePermissao($permissao);
      return redirect()->back();
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      if(Gate::denies('papel-create')){
        abort(403,"Não autorizado!");
      }

      $caminhos = [
      ['url'=>'/admin','titulo'=>'Admin'],
      ['url'=>route('papeis.index'),'titulo'=>'Papéis'],
      ['url'=>'','titulo'=>'Adicionar']
      ];

      return view('admin.papel.adicionar',compact('caminhos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      if(Gate::denies('papel-create')){
        abort(403,"Não autorizado!");
      }
      if($request['nome'] && $request['nome'] != "Admin"){
          Papel::create($request->all());

          return redirect()->route('papeis.index');
      }

      return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      if(Gate::denies('papel-edit')){
        abort(403,"Não autorizado!");
      }
      if(Papel::find($id)->nome == "Admin"){
          return redirect()->route('papeis.index');
      }

      $registro = Papel::find($id);

      $caminhos = [
      ['url'=>'/admin','titulo'=>'Admin'],
      ['url'=>route('papeis.index'),'titulo'=>'Papéis'],
      ['url'=>'','titulo'=>'Editar']
      ];

      return view('admin.papel.editar',compact('registro','caminhos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      if(Gate::denies('papel-edit')){
        abort(403,"Não autorizado!");
      }

      if(Papel::find($id)->nome == "Admin"){
          return redirect()->route('papeis.index');
      }
      if($request['nome'] && $request['nome'] != "Admin"){
        Papel::find($id)->update($request->all());
      }

      return redirect()->route('papeis.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      if(Gate::denies('papel-delete')){
        abort(403,"Não autorizado!");
      }

      if(Papel::find($id)->nome == "Admin"){
          return redirect()->route('papeis.index');
      }
      Papel::find($id)->delete();
      return redirect()->route('papeis.index');
    }
}

resources/views/admin/papel/_form.blade.php
<div class="input-field">
	<input type="text" name="nome" class="validade" value="{{ isset($registro->nome) ? $registro->nome : '' }}">
	<label>Nome do papel</label>
</div>

<div class="input-field">
	<input type="text" name="descricao" class="validade" value="{{ isset($registro->descricao) ? $registro->descricao : '' }}">
	<label>Descrição</label>
</div>

resources/views/admin/papel/adicionar.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h2 class="center">Adicionar Papel</h2>

	@include('admin._caminho')
	
	<div class="row">
		<form action="{{ route('papeis.store') }}" method="post">

		{{csrf_field()}}
		@include('admin.papel._form')

		<button class="btn green">Adicionar</button>

			
		</form>
			
	</div>
	
</div>
	

@endsection

resources/views/admin/papel/editar.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h2 class="center">Editar Papel</h2>
	@include('admin._caminho')
	<div class="row">
		<form action="{{ route('papeis.update',$registro->id) }}" method="post">

		{{csrf_field()}}
		{{ method_field('PUT') }}
		@include('admin.papel._form')

		<button class="btn blue">Atualizar</button>

			
		</form>
			
	</div>
	
</div>
	

@endsection

resources/views/admin/papel/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<h2 class="center">Lista de Papéis</h2>

		@include('admin._caminho')
		<div class="row">
			<table>
				<thead>
					<tr>
						<th>Id</th>
						<th>Nome</th>
						<th>Descrição</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
				@foreach($registros as $registro)
					<tr>
						<td>{{ $registro->id }}</td>
						<td>{{ $registro->nome }}</td>
						<td>{{ $registro->descricao }}</td>

						<td>


							<form action="{{route('papeis.destroy',$registro->id)}}" method="post">
								@can('papel-edit')
								<a title="Editar" class="btn orange" href="{{ route('papeis.edit',$registro->id) }}"><i class="material-icons">mode_edit</i></a>
								<a title="Permissões" class="btn blue" href="{{route('papeis.permissao',$registro->id)}}"><i class="material-icons">lock_outline</i></a>
								@endcan
								@can('papel-delete')
									{{ method_field('DELETE') }}
									{{ csrf_field() }}
									<button title="Deletar" class="btn red"><i class="material-icons">delete</i></button>
								@endcan
							</form>








						</td>
					</tr>
				@endforeach
				</tbody>
			</table>

		</div>
		<div class="row">
			@can('papel-create')
			<a class="btn blue" href="{{route('papeis.create')}}">Adicionar</a>
			@endcan
		</div>
	</div>

@endsection

resources/views/admin/papel/permissao.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<h2 class="center">Lista de Permissões para {{$papel->nome}}</h2>

		@include('admin._caminho')

		<div class="row">
			<form action="{{route('papeis.permissao.store',$papel->id)}}" method="post">
			{{ csrf_field() }}
			<div class="input-field">
				<select name="permissao_id">
					@foreach($permissao as $valor)
					<option value="{{$valor->id}}">{{$valor->nome}}</option>
					@endforeach
				</select>
			</div>
				<button class="btn blue">Adicionar</button>
			</form>


		</div>

		<div class="row">
			<table>
				<thead>
					<tr>

						<th>Permissão</th>
						<th>Descrição</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
				@foreach($papel->permissoes as $permissao)
					<tr>
						<td>{{ $permissao->nome }}</td>
						<td>{{ $permissao->descricao }}</td>

						<td>

							<form action="{{route('papeis.permissao.destroy',[$papel->id,$permissao->id])}}" method="post">
									{{ method_field('DELETE') }}
									{{ csrf_field() }}
									<button title="Deletar" class="btn red"><i class="material-icons">delete</i></button>
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>

		</div>

	</div>

@endsection